prefix : <http://qs.hocky.id/v/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix p: <https://qs.hocky.id/p/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?city ?prop ?val .
  ?val rdfs:label ?valLabel .
} WHERE {
  VALUES ?city { %(queries)s } .
  ?city ?prop ?val .
  OPTIONAL {
    ?val rdfs:label ?valLabel .
  }
}