prefix : <http://qs.hocky.id/v/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix p: <https://qs.hocky.id/p/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
  #DISTINCT ?universityID ?universityName ?city
DISTINCT  *
WHERE {
  VALUES ?universityID { :Q1257946} .
  #  VALUES ?universityID {%(queries)s} .
  ?universityID rdfs:label ?universityName .
  OPTIONAL {
    ?universityID p:inCity ?city .
    ?city rdfs:label ?cityLabel .
    ?city p:inCountry ?country .
    ?country rdfs:label ?countryLabel
  }
  OPTIONAL {
    ?universityID p:hasLink ?link
  }
  OPTIONAL {
    ?universityID p:hasLogo ?logo
  }
  OPTIONAL {
    ?universityID a ?type .
    ?type rdfs:label ?typeName
  }
  OPTIONAL {
    ?universityID p:hasResearchOutput ?researchOutput
  }
  OPTIONAL {
    ?universityID p:hasStudentFacultyRatio ?studentFacultyRatio
  }
  OPTIONAL {
    ?universityID p:hasFaculty ?facultyCount
  }
  OPTIONAL {
    ?universityID p:hasSize ?size
  }
  OPTIONAL {
    ?universityID p:hasInternationalStudent ?internationalStudent
  }
  OPTIONAL {
    ?universityID owl:sameAs ?wikidata
  }
  OPTIONAL {
    ?universityID p:hasAwards ?award .
    ?award rdfs:label ?awardLabel
  }
}

prefix : <http://qs.hocky.id/v/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix p: <https://qs.hocky.id/p/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
  #DISTINCT ?universityID ?universityName ?city
DISTINCT  *
WHERE {
  VALUES ?universityID { :Q1257946} .
  #  VALUES ?universityID {%(queries)s} .
  ?universityID rdfs:label ?universityName .
  OPTIONAL {
    ?universityID p:inCity ?city .
    ?city rdfs:label ?cityLabel .
    ?city p:inCountry ?country .
    ?country rdfs:label ?countryLabel
  }
  OPTIONAL {
    ?universityID p:hasLink ?link
  }
  OPTIONAL {
    ?universityID p:hasLogo ?logo
  }
  OPTIONAL {
    ?universityID a ?type .
    ?type rdfs:label ?typeName
  }
  OPTIONAL {
    ?universityID p:hasResearchOutput ?researchOutput
  }
  OPTIONAL {
    ?universityID p:hasStudentFacultyRatio ?studentFacultyRatio
  }
  OPTIONAL {
    ?universityID p:hasFaculty ?facultyCount
  }
  OPTIONAL {
    ?universityID p:hasSize ?size
  }
  OPTIONAL {
    ?universityID p:hasInternationalStudent ?internationalStudent
  }
  OPTIONAL {
    ?universityID owl:sameAs ?wikidata
  }
  OPTIONAL {
    ?universityID p:hasAwards ?award .
    ?award rdfs:label ?awardLabel
  }
}